different static code analysis fixes
continental/ecal pull request #132
Opened 2020-11-21 19:07 UTC by schilasky

* std::list -> std::vector (if possible)
* new -> std::make_shared / std::make_unique

2020-11-23 07:33 UTC, FlorianReimold requested changes
I don't think that I agree with the static code analysis tool (If that code really is what it suggested). Maybe I am wrong, but why would you alyways write:

```
std::shared_ptr<t> = std::sdhared_ptr<t>(std::make_shared<t>())
```

instead of 

```
std::shared_ptr<t> = std::make_shared<t>()
```
?

The first version (that's the version you got suggested from the static code analysis) includes an unnecessary copy construction and looks quite redundant.

And are you sure that you can always replace `std::list` with `std::vector` without hurting the insertion performance? To my knowledge an `std::list` offers constant time O(1) insertion and removal, while an `std::vector` is reallocated every time you hit the pre-allocated limit, which *can* hurt the performance with large lists that are dynamically growing or shrinking.

2020-11-23 07:33 UTC, FlorianReimold commented on app/rec/rec_client_cli/src/ecal_rec_cli.cpp
> +    std::vector<const eCAL::rec::JobStatus*> flushing_jobs_;
I am curious, why would you change this to an std::vector? Why did the static code analysis show this as an issue?

A Vector may have to be reallocated multiple times when back-inserting elements like in this loop. An std::list will never have to be reallocated (it offers constant time insertion at any position). Sure, a vector will offer constant time random access of any element, but the elements aren't ever accessed, only the size of the list is used. In my optinion the old code was more performant (CPU wise, it will use more memory, though). The improvement that will be faster and use less memory would be replacing the `std::list` / `std::vector` with an `int`, as the content of the list doesn't matter anyways.

2020-11-23 07:33 UTC, FlorianReimold commented on ecal/core/src/readwrite/ecal_reader.cpp
> +    std::shared_ptr<std::list<std::string>> loc_timeouts = std::shared_ptr<std::list<std::string>>(std::make_shared<std::list<std::string>>());
Isn't the output of std::make_shared already a shared_ptr of the correct type? Why would you copy-construct a new shared_ptr from that again?

2020-11-23 07:33 UTC, FlorianReimold commented on ecal/core/src/readwrite/ecal_writer.cpp
> +    std::shared_ptr<std::list<std::string>> loc_timeouts = std::shared_ptr<std::list<std::string>>(std::make_shared<std::list<std::string>>());
Isn't the output of std::make_shared already a shared_ptr of the correct type? Why would you copy-construct a new shared_ptr from that again?

2020-11-23 07:33 UTC, FlorianReimold commented on ecal/core/src/ecal_globals.cpp
> +        log_instance = std::unique_ptr<CLog>(std::make_unique<CLog>());
Isn't the output of std::make_unique already a unique_ptr of the correct type? Why would you copy-construct a new shared_ptr from that again?

2020-11-23 07:33 UTC, FlorianReimold commented on ecal/core/src/ecal_globals.cpp
> +        monitoring_instance = std::unique_ptr<CMonitoring>(std::make_unique<CMonitoring>());
Isn't the output of std::make_unique already a unique_ptr of the correct type? Why would you copy-construct a new shared_ptr from that again?

2020-11-23 07:33 UTC, FlorianReimold commented on ecal/core/src/ecal_globals.cpp
> +        timegate_instance = std::unique_ptr<CTimeGate>(std::make_unique<CTimeGate>());
Isn't the output of std::make_unique already a unique_ptr of the correct type? Why would you copy-construct a new shared_ptr from that again?

2020-11-23 08:19 UTC, rex-schilasky commented on app/rec/rec_client_cli/src/ecal_rec_cli.cpp
> +    std::vector<const eCAL::rec::JobStatus*> flushing_jobs_;
Yes that what I expected too. But the static code analysis suggests to always use vectors instead lists if there are push_backs only. Check this article [std::list vs std::vector performance](https://dzone.com/articles/c-benchmark-%E2%80%93-stdvector-vs#:~:text=std%3A%3Avector%20always%20performs,or%20inserting%20in%20the%20front) and that [one](https://www.viva64.com/en/w/v826/print/) from PVS itself.

I mean it doesnt matter that much in our use cases, but it's faster :).

2020-11-23 08:23 UTC, rex-schilasky commented on ecal/core/src/readwrite/ecal_reader.cpp
> +    std::shared_ptr<std::list<std::string>> loc_timeouts = std::shared_ptr<std::list<std::string>>(std::make_shared<std::list<std::string>>());
It's about optimized object allocation and avoiding memory leaks in case of an exception. That is my understanding. See [here](https://www.viva64.com/en/w/v824/print/)

2020-11-23 12:00 UTC, rex-schilasky commented on ecal/core/src/readwrite/ecal_reader.cpp
> +    std::shared_ptr<std::list<std::string>> loc_timeouts = std::shared_ptr<std::list<std::string>>(std::make_shared<std::list<std::string>>());
Now (after our discussion) I got it. Next commit will remove the unnecessary extra casts.

2020-11-25 10:00 UTC, FlorianReimold approved these changes
Looks good 👍

2020-11-25 10:42 UTC, merged