Added callback calls on CallAsync service errors
continental/ecal pull request #375
Opened 2021-08-30 13:06 UTC by brakmic-aleksandar

**Pull request type**

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

**What is the current behavior?**
When client calls service which doesn't exist/isn't initiated yet it fails silently.

Issue Number: #371

**What is the new behavior?**
Client will let user know that it couldn't connect to service through callback.

**Does this introduce a breaking change?**

- [ ] Yes
- [x] No

2021-08-30 13:15 UTC, FlorianReimold commented
This adds a new API function right? Wich would mean it breaks ABI compatibility :/

2021-08-30 13:35 UTC, brakmic-aleksandar commented
@FlorianReimold It adds private function to impl class which should prevent breakage of ABI compatibility, if i'm not mistaken.

2021-09-01 06:05 UTC, rex-schilasky commented
For the new ` CServiceClientImpl::CallAsync` methods I would prefer the return type `bool` too. Like there counterpart signatures `bool CServiceClientImpl::Call`.

2021-09-01 06:09 UTC, rex-schilasky requested changes

2021-09-01 06:09 UTC, rex-schilasky commented on ecal/core/src/service/ecal_service_client_impl.cpp
>    void CServiceClientImpl::CallAsync(const std::string& host_name_, const std::string& method_name_, const std::string& request_)
`bool CServiceClientImpl::CallAsync`

2021-09-03 06:37 UTC, merged