minor doc fixes for building from sources (ubuntu)
continental/ecal pull request #547
Opened 2022-03-09 15:17 UTC by rex-schilasky

Fix some minor documentation issues for Ubuntu build

**Pull request type**

 

 

Please check the type of change your PR introduces:
- [X] Documentation content changes

**What is the new behavior?**

Some minor fixes - ubuntu only. Moved installing python dependencies in Ubuntu16/18/20 section. Add some comments regarding python CMake options.

2022-03-09 15:39 UTC, FlorianReimold requested changes

2022-03-09 15:39 UTC, FlorianReimold commented on doc/rst/development/building_ecal_from_source.rst
> +      sudo apt-get install python3.8-dev python3-pip
Hm, moving the dependencies from the "Install dependencies" Section into the "Build" Section doesn't really make sense. Additionally, those dependencies will only work For Ubnutu 20.04, das it specifies python 3.8.

Maybe we should add an entire "Build python language binding" section?

2022-03-09 15:55 UTC, rex-schilasky commented on doc/rst/development/building_ecal_from_source.rst
> +      sudo apt-get install python3.8-dev python3-pip
Yes maybe. In the build section it's not fitting that is true. But for 20.04 it was missing in general. We describe it for 18.04 (as now) with the 3.6 version and additional for 20.04 with 3.8 under "install dependencies". What do you mean ?

2022-03-10 11:42 UTC, FlorianReimold approved these changes

2022-03-10 12:02 UTC, merged