Enable local clang-tidy scan on Linux
continental/ecal pull request #579
Opened 2022-03-28 12:22 UTC by OrhanKupusoglu

**Pull request type**

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

**What is the current behavior?**

Local clang-tidy scan is not available.

**What is the new behavior?**

- This feature branch is prepared for Linux, and tested on Ubuntu 20.04.
- Clang-tidy is NOT triggered with CMake's **CMAKE_CXX_CLANG_TIDY**, because this way no exclusion in source and header files are possible.
- Requires Python 3.6+.
- CMake generates the 'compile_commands.json' file.
- Excluded directories are given by 'excludes_clang_tidy.json'.
- This JSON file is filtered into JSON files, one for included and the other for excluded source files.
- In this new JSON file included headers are also searched for the excluded subdirectories, "-I" is replaced with "-isystem ".
- The new JSON file is used by clang-tidy. 
- A Bash script, 'build.sh' is provided for convenience.

**Does this introduce a breaking change?**

- [ ] Yes
- [x] No

**Other information**

With a Windows counterpart of 'build.sh', it may work on Windows as a CLI tool.

2022-03-28 13:49 UTC, Kerstin-Keller commented on CMakeLists.txt
> +set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
I'd prefer that this would be set from outside , e.g. the build scripts / batch / bash files,
 with `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`

2022-03-28 16:28 UTC, OrhanKupusoglu commented on CMakeLists.txt
> +set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
1. Done

2022-03-31 09:05 UTC, OrhanKupusoglu commented
This is the latest help:
```
$ ./build.sh --help
build.sh [-h|-help] [-o|compiler <C> <CXX>] [-m|--make] [-d|--database]
run cmake, and then optinonally make or clang-tidy - where:
    -h | --help                 show this help message and exit
    -o | --compiler <C> <CXX>   set C & CXX compiler paths
    -m | --make                 run make
    -d | --database             run clang-tidy on the compilation database

```

2022-03-31 09:17 UTC, OrhanKupusoglu commented
This is the latest help:
```
$ ./build.sh --help
build.sh [-h|-help] [-o|compiler <C> <CXX>] [-m|--make] [-d|--database]
run cmake, and then optionally make and/or clang-tidy - where:
    -h | --help                 show this help message and exit
    -c | --compiler <C> <CXX>   set C & CXX compiler paths
    -m | --make                 run make
    -d | --database             run clang-tidy on the compilation database

```

2022-03-31 09:19 UTC, OrhanKupusoglu commented
This is the latest help:
```
$ ./build.sh --help
build.sh [-h|-help] [-c|compiler <C> <CXX>] [-m|--make] [-d|--database]
run cmake, and then optionally make and/or clang-tidy - where:
    -h | --help                 show this help message and exit
    -c | --compiler <C> <CXX>   set C & CXX compiler paths
    -m | --make                 run make
    -d | --database             run clang-tidy on the compilation database

```

2022-03-31 11:50 UTC, Kerstin-Keller requested changes
Hi @OrhanKupusoglu,

well done, very nice and clean code.
I do have a few remarks though. First, for the python script, it would be beneficial to have input / output arguments, so it can possibly be reused in other contexts.

Then I am not sure about the file structure, as all files are now placed in the root directory of CMake. By all means, the complete eCAL folder structure could use some cleanup, still I would not put all files in the main directory.
We do have a `build_win` folder, maybe ist makes sense to have a `build` / `build_scripts` folder instead and move at least `build.sh` / `filter_clang_tidy.py` / `excludes_clang_tidy.json` into that subdirectory? (Or even `build/clang-tidy` and all mentioned files in that subdirectory? I think it might help.

2022-03-31 11:50 UTC, Kerstin-Keller commented on filter_clang_tidy.py
> +
Can you please not hardcode these paths but make them arguments to the python script?
(see https://docs.python.org/3/library/argparse.html)

2022-03-31 11:56 UTC, Kerstin-Keller commented
Maybe it's worth trying out this as part of CI https://github.com/marketplace/actions/clang-tidy-review - just incremental checks for PRs.

2022-03-31 17:42 UTC, OrhanKupusoglu commented
Thanks for the review.
The scripts are moved to the new **./build_linux/clang-tidy/** directory.
This alone made some changes in the Shell script and Python script.
The Shell script is also refactored for readability with function definitions.
The Python script can read two arguments, but default values are OK:
```
$ python3 filter_clang_tidy.py --help
usage: filter_clang_tidy.py [-h] [--build BUILD] [--config CONFIG]

Filter compilation database

optional arguments:
  -h, --help       show this help message and exit
  --build BUILD    rel/abs path of the build directory (default: ../../_build)
  --config CONFIG  rel/abs path of the config JSON file (default: excludes_clang_tidy.json)
```

2022-03-31 17:48 UTC, OrhanKupusoglu commented
> Maybe it's worth trying out this as part of CI https://github.com/marketplace/actions/clang-tidy-review - just incremental checks for PRs. - You could try it in your fork!

Thanks for the comment.
This PR is for local static analysis, which might be useful for developers, but I am also working on static analysis for PRs.
This is a useful link, danke schön.

2022-03-31 17:53 UTC, OrhanKupusoglu commented on filter_clang_tidy.py
> +
Thanks for the link.
I think that I have completed your request.
Please check commit [d5da39f](https://github.com/continental/ecal/pull/579/commits/d5da39fabdb8a8600f34167dcecba83f6ebbe6ae)

2022-04-01 11:17 UTC, OrhanKupusoglu commented on filter_clang_tidy.py
> +
The python script uses **compile_database.json** as it is, because this is a CMake generated artifact.
But the shell script was not reading the build path, fixed now with some ugly bash string manipulation.
```
$ ./build.sh --help
build.sh [-h|-help] [-b|--build] [-c|compiler <C> <CXX>] [-m|--make] [-d|--database]
run cmake, and then optionally make and/or clang-tidy - where:
    -h | --help                 show this help message and exit
    -b | --build                build path rel to root dir, default: '../../_build'
    -c | --compiler <C> <CXX>   set C & CXX compiler paths
    -m | --make                 run make
    -d | --database             run clang-tidy on the compilation database

```

2022-04-11 17:05 UTC, OrhanKupusoglu commented
Now a list of files can be scanned, this capability is utilized by a GitHub action to scan added or modified files.
```
$ cd build_linux/clang-tidy/

$ ./build.sh --help
build.sh [-h|-help] [-b|--build <build>] [-c|compiler <C> <CXX>] [-m|--make] [-i|--filter <app> <cfg>] [-d|--database] [-f|--files <files...>]
run cmake, and then optionally make and/or clang-tidy - where:
    -h | --help                 show this help message and exit
    -b | --build <build>        build path relative to this script, default: '../../_build'
    -c | --compiler <C> <CXX>   set C & CXX compiler paths
    -m | --make                 run make
    -i | --filter <app> <cfg>   filtering app & its config rel. to this script or abs. paths, default: 'filter_clang_tidy.py excludes_clang_tidy.json'
    -d | --database             run clang-tidy on the compilation database
    -f | --files <files...>     run clang-tidy on the given files (remaining args)

$ python3 filter_clang_tidy.py --help
usage: filter_clang_tidy.py [-h] [--build BUILD] [--config CONFIG] [--isystem]

Filter compilation database.

optional arguments:
  -h, --help       show this help message and exit
  --build BUILD    rel/abs path of the build directory (default: ../../_build)
  --config CONFIG  rel/abs path of the config JSON file (default: excludes_clang_tidy.json)
  --isystem        convert includes from -I to -isystem (default: False)
```

2022-04-21 09:49 UTC, OrhanKupusoglu commented
If already built, then there is no need to generate cmake and protobuf files again.
This option is useful to run clang-tidy after a build.
Instead of running a stand-alone workflow, after building eCAL on Ubuntu 20.04 clang-tidy may be run in the same workflow. 
```
$ build_linux/clang-tidy/build.sh --help
build.sh [-h|-help] [-b|--build <build>] [-c|compiler <C> <CXX>] [-m|--make] [-i|--filter <app> <cfg>] [-d|--database] [-a|--already] [-f|--files <files...>]
run cmake, and then optionally make and/or clang-tidy - where:
    -h | --help                 show this help message and exit
    -b | --build <build>        build path relative to this script, default: '../../_build'
    -c | --compiler <C> <CXX>   set C & CXX compiler paths
    -m | --make                 run make
    -i | --filter <app> <cfg>   filtering app & its config rel. to this script or abs. paths, default: 'filter_clang_tidy.py' 'excludes_clang_tidy.json'
    -d | --database             run clang-tidy on the compilation database
    -a | --already              already built, all machine-generated codes are available
    -f | --files <files...>     run clang-tidy on the given files (remaining args)
```

2022-04-22 12:39 UTC, OrhanKupusoglu commented
I gave the [clang-tidy-review](https://github.com/marketplace/actions/clang-tidy-review) a cursory look, for now it fails with Docker errors.
Ubuntu 22.04 Jammy Jellyfish is released on April 21, 2022.
Displaying clang-tidy warnings as code-review messages using the GitHub API is a good idea.
 
```
Build container for action use: '/home/runner/work/_actions/ZedThree/clang-tidy-review/v0.8.2/Dockerfile'.
...
  /usr/bin/docker build -t 294b31:369a0b4ff8d340e68e187d4dd2105431 -f "/home/runner/work/_actions/ZedThree/clang-tidy-review/v0.8.2/Dockerfile" "/home/runner/work/_actions/ZedThree/clang-tidy-review/v0.8.2"
  Sending build context to Docker daemon  152.1kB
  
  Step 1/5 : FROM ubuntu:latest
   ---> 3f4714ee068a
  Step 2/5 : COPY requirements.txt /requirements.txt
   ---> Using cache
   ---> faf2fb89e4a9
  Step 3/5 : RUN apt update &&     DEBIAN_FRONTEND=noninteractive     apt-get install -y --no-install-recommends    build-essential cmake git     tzdata     clang-tidy-6.0     clang-tidy-7     clang-tidy-8     clang-tidy-9     clang-tidy-10     clang-tidy-11     clang-tidy-12     python3 python3-pip &&     pip3 install --upgrade pip &&     pip3 install -r requirements.txt
   ---> Running in 623e5fcce3e9
  
  WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
  
  Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
  Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [90.7 kB]
  Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [90.7 kB]
  Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [90.7 kB]
  Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]
  Get:6 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
  Get:7 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
  Get:8 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
  Fetched 20.2 MB in 1s (13.9 MB/s)
  Reading package lists...
  Building dependency tree...
  Reading state information...
  All packages are up to date.
  Reading package lists...
  Building dependency tree...
  Reading state information...
  E: Unable to locate package clang-tidy-6.0
  E: Couldn't find any package by glob 'clang-tidy-6.0'
  E: Couldn't find any package by regex 'clang-tidy-6.0'
  E: Unable to locate package clang-tidy-7
  E: Unable to locate package clang-tidy-8
  E: Unable to locate package clang-tidy-9
  E: Unable to locate package clang-tidy-10
  The command '/bin/sh -c apt update &&     DEBIAN_FRONTEND=noninteractive     apt-get install -y --no-install-recommends    build-essential cmake git     tzdata     clang-tidy-6.0     clang-tidy-7     clang-tidy-8     clang-tidy-9     clang-tidy-10     clang-tidy-11     clang-tidy-12     python3 python3-pip &&     pip3 install --upgrade pip &&     pip3 install -r requirements.txt' returned a non-zero code: 100
  
Error: Docker build failed with exit code 100
```

2022-04-26 11:51 UTC, OrhanKupusoglu commented on filter_clang_tidy.py
> +
I think that the current state of the scripts fulfills this code-review request.

2022-04-26 16:20 UTC, OrhanKupusoglu commented
[Run clang-tidy #8](https://github.com/continental/ecal/runs/6177040457?check_suite_focus=true) did fail.

This was unexpected, because this action uses the same apt-get install line as Build Ubuntu 20.04 action, it just additionally installs clang-tidy.

I re-ordered the output lines for better readability:
```
CMake Error at CMakeLists.txt:172 (_find_package):
  Could not find a package configuration file provided by "Qt5Svg" with any
  of the following names:

    Qt5SvgConfig.cmake
    qt5svg-config.cmake

  Add the installation prefix of "Qt5Svg" to CMAKE_PREFIX_PATH or set
  "Qt5Svg_DIR" to a directory containing one of the above files.  If "Qt5Svg"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /usr/lib/x[86](https://github.com/continental/ecal/runs/6177040457?check_suite_focus=true#step:6:86)_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  CMakeLists.txt:172 (_find_package)
  thirdparty/qwt/CMakeLists.txt:4 (find_package)
```
The failure is similar to the one in the comment I wrote for the pull-request [Made Qt5-msvc-code MSVC-only #599](https://github.com/continental/ecal/pull/599#issuecomment-1093002758). 
It looks like **libqt5svg5-dev** is missing.
```
$ apt-file search Qt5SvgConfig.cmake
libqt5svg5-dev: /usr/lib/x86_64-linux-gnu/cmake/Qt5Svg/Qt5SvgConfig.cmake
```
Maybe installing the whole **libqt5\*-dev** family is a good idea.

2022-05-04 13:19 UTC, OrhanKupusoglu commented
On [Build Ubuntu 20.04 #1831](https://github.com/continental/ecal/actions/runs/2264266913) the size of the directory bundle is 34.2 MB.
Previously without exclusions the size was 710 MB, so a huge reduction was achieved. 
The major culprit was the **.git** directory.

2022-05-09 15:12 UTC, merged