Config: Set network_mode=false by default
continental/ecal pull request #587
Opened 2022-03-30 12:24 UTC by FlorianReimold

- Set `network_mode = false` by default in `ecal.ini`
- Documented that since eCAL 5.10 you will have to also set the network mode to `true` again for it to work properly

2022-03-30 12:50 UTC, Kerstin-Keller requested changes
@FlorianReimold probably you also need to modify https://github.com/continental/ecal/blob/b8a681d7504828d9de7dc592a388a628ffe34a4c/ecal/core/src/ecal_def.h#L62
Also I don't know whats up with the `CFG_FORCE_DEFAULT_LOCAL` variable, if we need to set something in CMake (ok, its only reference is in that `ecal_def.h` file, so I would remove it altogether).

2022-03-30 13:24 UTC, FlorianReimold commented
Here is what CFG_FORCE_DEFAULT_LOCAL does (refactored):

```cpp
#ifdef CFG_FORCE_DEFAULT_LOCAL
  #define NET_ENABLED                  false
  #define NET_UDP_MULTICAST_TTL        0
  #define NET_UDP_MC_REC_ENABLED       false
  #define PUB_USE_UDP_MC               0
#else
  #define NET_ENABLED                  true
  #define NET_UDP_MULTICAST_TTL        3
  #define NET_UDP_MC_REC_ENABLED       true
  #define PUB_USE_UDP_MC               2
#endif
```

so basically it
- sets the multicast ttl to 0 (which is not required when network mode is turned off. I also decided to leave it at 2 in the `ecal.ini` because it always is a case for errors when someone sets network to ON but forgets to increase the multicast ttl)
- disables sending and receiving UDP traffic

it does not disable sending and receiving TCP traffic though, which is inconsistent.

I would vote for either removing the `CFG_FORCE_DEFAULT_LOCAL` entirely or restricting it to only modify the `NET_ENABLED` define

2022-03-30 14:34 UTC, Kerstin-Keller commented
I would vote to remove it completely. At somepoint we used to have two different ini files, which one could be chosen to install.
I  mean this is the fallback in case no ini file is found, or the value is not present in the ini file.
Let's remove it, and at some point, we can revisit it. We could then also consider to have a single source of truth (e.g. to generate (CMake) the ini file & the def.h file)

2022-03-31 12:51 UTC, Kerstin-Keller commented on ecal/core/src/ecal_def.h
>  #define NET_UDP_MC_REC_ENABLED                      true
@FlorianReimold but shouldn't we have kept the `false` value?

2022-03-31 14:03 UTC, FlorianReimold commented on ecal/core/src/ecal_def.h
>  #define NET_UDP_MC_REC_ENABLED                      true
I wanted it to be the same as the default `ecal.ini`. When `network` is `false`, the multicast receiver is should not be used anyways, so it is unnecessary to turn it off separetely

2022-03-31 14:45 UTC, Kerstin-Keller commented on ecal/core/src/ecal_def.h
>  #define NET_UDP_MC_REC_ENABLED                      true
ah sorry I confused it with the `NET_ENABLED` parameter....

2022-03-31 14:46 UTC, Kerstin-Keller approved these changes

2022-04-01 06:26 UTC, rex-schilasky approved these changes

2022-04-01 07:00 UTC, merged