dynamic service client
continental/ecal pull request #598
Opened 2022-04-07 16:02 UTC by rex-schilasky

**Pull request type**

 

 

Please check the type of change your PR introduces:
- [X] Feature

**What is the current behavior?**
Service method message type descriptions are not part of the registration and are not available by any kind of user API.

Issue Number: #456

**What is the new behavior?**
Service method message type descriptions can be set using a new CServiceServer API method and are added to the registration information of a eCAL server entity. A new eCAL::Util API function will make this information available.

2022-04-14 12:22 UTC, Kerstin-Keller reviewed
In general, this looks quite good!
However, constructing the decoder and the prototypes are in general quite expensive operations from what I know (haven't debugged it though).
It might make sense to construct an object (with `msg_desc_` and `msg_type`), and then have the two conversion functions as member functions.
I guess it depends on how frequently you will want to convert between JSON and serialized messages.

2022-04-20 09:59 UTC, FlorianReimold requested changes

2022-04-20 09:59 UTC, FlorianReimold commented on contrib/ecalproto/include/ecal/protobuf/ecal_proto_dyn.h
> +    google::protobuf::Message* GetProtoMessageFromDescriptor(const std::string& msg_desc_, const std::string& msg_type_, std::string& error_s_);
This looks like it returns a pointer to some heap-allocated memory that the user has to manage. We should document that the user has to free that memory!

Like here:
https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message#Message.New.details

We should also document that this function can return a `nullptr` in certain cases.

A better way would probably be to return a smart pointer to prevent the user from leaking memory.

2022-04-20 09:59 UTC, FlorianReimold commented on ecal/core/include/ecal/ecal_util.h
> +    [[deprecated]]
We should tell the user which function to use now instead of this deprecated one

2022-04-20 09:59 UTC, FlorianReimold commented on ecal/core/include/ecal/msg/protobuf/server.h
> +        auto req_msg = msg_decoder.GetProtoMessageFromDescriptorSet(pset, type_name_, error_s_);
I guess this causes a memory leak, right? Or is it deleted somewhere?

2022-04-20 10:00 UTC, FlorianReimold commented on ecal/core/include/ecal/ecal_util.h
> +    [[deprecated]]
Oh, and it would be really cool to have something like "Deprecated since 5.10" somewhere

2022-04-20 10:39 UTC, rex-schilasky commented on contrib/ecalproto/include/ecal/protobuf/ecal_proto_dyn.h
> +    google::protobuf::Message* GetProtoMessageFromDescriptor(const std::string& msg_desc_, const std::string& msg_type_, std::string& error_s_);
I can improve the documentation here. I just added one more member function to `eCAL::CProtoDynDecoder`. Some of these functions return this kind of raw message pointer to a `google::protobuf::message`. The memory is handled inside `CProtoDynDecoder` and is valid as long the decoder instance exists (it's using an instance of `google::protobuf::DescriptorPool` internally).

We could make a copy using suggested `Message::New()`, but maybe it's better to just better document the right usage of `eCAL::CProtoDynDecoder`.

2022-04-21 06:28 UTC, rex-schilasky commented on ecal/core/include/ecal/msg/protobuf/server.h
> +        auto req_msg = msg_decoder.GetProtoMessageFromDescriptorSet(pset, type_name_, error_s_);
It should be deleted with the destruction of `pset`.

2022-04-21 06:59 UTC, rex-schilasky commented on ecal/core/include/ecal/ecal_util.h
> +    [[deprecated]]
Done, I add some more documentation in ecal_util.h

2022-04-21 10:02 UTC, FlorianReimold commented on ecal/core/include/ecal/msg/protobuf/server.h
> +        auto req_msg = msg_decoder.GetProtoMessageFromDescriptorSet(pset, type_name_, error_s_);
The pointer goes out of scope without calling delete.

2022-04-25 14:26 UTC, FlorianReimold approved these changes

2022-04-26 06:47 UTC, merged