Added Monitor plugin for 2D plots of arbitrary scalar values
continental/ecal pull request #607
Opened 2022-04-11 13:18 UTC by FlorianReimold

Fixes #434

2022-04-13 10:55 UTC, hannemn requested changes

2022-04-13 10:55 UTC, hannemn commented on app/mon/mon_plugins/signals_plotting/src/util.h
> +  enum PLUGIN_STATE : int
```suggestion
  enum class PLUGIN_STATE : int
```

2022-04-13 10:55 UTC, hannemn commented on app/mon/mon_plugins/signals_plotting/src/chart_widget.h
> +  #include <math.h>
The <cmath> should be also available on linux, since it is part of the c++ standard library.

2022-04-13 10:55 UTC, hannemn commented on app/mon/mon_plugins/signals_plotting/src/util.h
> +  enum PLUGIN_STATE : int
Use the type-safe alternative "enum class".

2022-04-13 10:55 UTC, hannemn commented on CMakeLists.txt
> +  option(ECAL_THIRDPARTY_BUILD_QWT               "Build qwt::qwt with eCAL"                                          ON)
```suggestion
  option(ECAL_THIRDPARTY_BUILD_QWT             "Build qwt::qwt with eCAL"                                          ON)
```

2022-04-13 10:55 UTC, hannemn commented on CMakeLists.txt
> +  option(ECAL_THIRDPARTY_BUILD_QWT               "Build qwt::qwt with eCAL"                                        OFF)
```suggestion
  option(ECAL_THIRDPARTY_BUILD_QWT             "Build qwt::qwt with eCAL"                                          OFF)
```

2022-04-15 07:55 UTC, adriana-chirila commented on app/mon/mon_plugins/signals_plotting/src/util.h
> +  enum PLUGIN_STATE : int
fixed with [76d1d72](https://github.com/continental/ecal/pull/607/commits/76d1d7238c1c6e50c36d71c1c86362f106e0b241)

2022-04-15 07:56 UTC, adriana-chirila commented on app/mon/mon_plugins/signals_plotting/src/chart_widget.h
> +  #include <math.h>
fixed with [76d1d72](https://github.com/continental/ecal/pull/607/commits/76d1d7238c1c6e50c36d71c1c86362f106e0b241)

2022-04-15 07:56 UTC, adriana-chirila commented on CMakeLists.txt
> +  option(ECAL_THIRDPARTY_BUILD_QWT               "Build qwt::qwt with eCAL"                                          ON)
fixed with [76d1d72](https://github.com/continental/ecal/pull/607/commits/76d1d7238c1c6e50c36d71c1c86362f106e0b241)

2022-04-15 07:56 UTC, adriana-chirila commented on CMakeLists.txt
> +  option(ECAL_THIRDPARTY_BUILD_QWT               "Build qwt::qwt with eCAL"                                        OFF)
fixed with [76d1d72](https://github.com/continental/ecal/pull/607/commits/76d1d7238c1c6e50c36d71c1c86362f106e0b241)

2022-04-20 08:08 UTC, merged