Fixed many clang-tidy warnings (from clang-analyzer-*)
continental/ecal pull request #667
Opened 2022-05-13 16:14 UTC by FlorianReimold

2022-05-17 12:41 UTC, FlorianReimold reviewed
I Looked over all files and added some inline comments where I felt that an additional pair of eyes is needed

2022-05-17 12:41 UTC, FlorianReimold commented on app/rec/rec_gui/src/qecalrec.cpp
> +  if (!success)
I guess this is not the proper way to solve this. I rather think that either line is redundand:

```
  bool success = rec_server_->SetHostFilter(hostname, host_filter);
  success = executeBlockingMethod<bool>([this, &hostname, &host_filter]() { return rec_server_->SetHostFilter(hostname, host_filter); }, widgetOf(sender()), omit_dialogs);
```

They appear to do the same.

2022-05-17 12:41 UTC, FlorianReimold commented on ecal/core/src/readwrite/ecal_reader.cpp
> +      else if ((m_clock - m_clock_old) > 0)
Honestly I like the previous version a little bit better.

2022-05-17 12:41 UTC, FlorianReimold commented on ecal/core/src/readwrite/ecal_reader_udp_mc.cpp
> -  template<> std::shared_ptr<CMulticastLayer> CReaderLayer<CMulticastLayer>::layer(nullptr);
Why was this in here after all? Was this some residue from ancient times that now can be removed safely?

2022-05-17 12:41 UTC, FlorianReimold commented on ecal/core/src/readwrite/ecal_reader_tcp.cpp
> -  template<> std::shared_ptr<CTCPReaderLayer> CReaderLayer<CTCPReaderLayer>::layer(nullptr);
Why was this in here after all? Was this some residue from ancient times that now can be removed safely?

2022-05-17 12:41 UTC, FlorianReimold commented on ecal/core/src/readwrite/ecal_reader_shm.cpp
> -  template<> std::shared_ptr<CSHMLayer> CReaderLayer<eCAL::CSHMLayer>::layer(nullptr);
Why was this in here after all? Was this some residue from ancient times that now can be removed safely?

2022-05-17 12:41 UTC, FlorianReimold commented on ecal/core/src/readwrite/ecal_reader_inproc.cpp
> -  template<> std::shared_ptr<CInProcLayer> CReaderLayer<CInProcLayer>::layer(nullptr);
Why was this in here after all? Was this some residue from ancient times that now can be removed safely?

2022-05-17 12:41 UTC, FlorianReimold commented on ecal/core/src/readwrite/ecal_reader_iceoryx.cpp
> -  template<> std::shared_ptr<CSHMLayer> CReaderLayer<CSHMLayer>::layer(nullptr);
Why was this in here after all? Was this some residue from ancient times that now can be removed safely?

2022-05-17 12:41 UTC, FlorianReimold commented on ecal/core/src/ecal_process.cpp
> +      if (true == zero_copy)
I don't understand this "improvement". Shouldn't you like always just use the boolean directly and not compare it to `true` or `false` manually?

2022-05-17 13:50 UTC, rex-schilasky commented on ecal/core/src/readwrite/ecal_reader_udp_mc.cpp
> -  template<> std::shared_ptr<CMulticastLayer> CReaderLayer<CMulticastLayer>::layer(nullptr);
This can not be removed because it is a the static global layer instance.

2022-05-19 10:16 UTC, FlorianReimold commented on ecal/core/src/readwrite/ecal_reader_udp_mc.cpp
> -  template<> std::shared_ptr<CMulticastLayer> CReaderLayer<CMulticastLayer>::layer(nullptr);
We tracked it back and this is fine

2022-05-19 10:16 UTC, FlorianReimold commented on ecal/core/src/readwrite/ecal_reader_tcp.cpp
> -  template<> std::shared_ptr<CTCPReaderLayer> CReaderLayer<CTCPReaderLayer>::layer(nullptr);
We tracked it back and this is fine

2022-05-19 10:16 UTC, FlorianReimold commented on ecal/core/src/readwrite/ecal_reader_shm.cpp
> -  template<> std::shared_ptr<CSHMLayer> CReaderLayer<eCAL::CSHMLayer>::layer(nullptr);
We tracked it back and this is fine

2022-05-19 10:16 UTC, FlorianReimold commented on ecal/core/src/readwrite/ecal_reader_iceoryx.cpp
> -  template<> std::shared_ptr<CSHMLayer> CReaderLayer<CSHMLayer>::layer(nullptr);
We tracked it back and this is fine

2022-05-19 10:17 UTC, FlorianReimold commented on ecal/core/src/readwrite/ecal_reader_inproc.cpp
> -  template<> std::shared_ptr<CInProcLayer> CReaderLayer<CInProcLayer>::layer(nullptr);
We tracked it back and this is fine

2022-05-19 10:17 UTC, FlorianReimold commented on ecal/core/src/readwrite/ecal_reader.cpp
> +      else if ((m_clock - m_clock_old) > 0)
I will leave the else if to prevent the clang-tidy warning.

2022-05-19 10:56 UTC, rex-schilasky requested changes

2022-05-19 11:08 UTC, FlorianReimold commented on ecal/core/include/ecal/ecal_qos.h
> +      QOS::eQOSPolicy_Reliability  reliability;               //!< qos reliability mode
It didn't give me any warning on my ubuntu 20 machine, so I removed it again

2022-05-19 11:10 UTC, FlorianReimold commented on ecal/core/src/ecal_process.cpp
> +      if (true == zero_copy)
I removed the true== part

2022-05-19 11:11 UTC, FlorianReimold commented on app/rec/rec_gui/src/qecalrec.cpp
> +  if (!success)
I removed the first call entirely, as it is a duplicate

2022-05-19 15:14 UTC, rex-schilasky approved these changes

2022-05-20 07:01 UTC, Kerstin-Keller approved these changes
See two minor comments.

2022-05-20 07:21 UTC, FlorianReimold commented on app/rec/rec_gui/src/widgets/wait_for_shutdown_dialog/wait_for_shutdown_dialog.cpp
>    // Bitwise-or is intended!
removed it

2022-05-20 07:21 UTC, FlorianReimold commented on app/rec/rec_server_cli/src/ecal_rec_server_cli.cpp
>      // bitwise-or is intended and necessary!
removed it

2022-06-01 08:02 UTC, merged